import Foundation

// Centralized string table for lightweight in-app localization.
struct AppStrings {
    let language: String

    static let availableLanguages = [
        "Español",
        "English (US)",
        "English (UK)",
        "Français",
        "Deutsch",
        "Italiano",
        "Português (PT)",
        "Nederlands"
    ]

    static let defaultLogText = "Selecciona una carpeta para comenzar."

    func text(_ key: String) -> String {
        AppStrings.translations[language]?[key] ?? AppStrings.translations["Español"]![key]!
    }

    private static let translations: [String: [String: String]] = [
        "Español": [
            "title": "Folder to Music",
            "subtitle": "Crea carpetas y playlists en Music a partir de una jerarquía de carpetas.",
            "language": "Idioma",
            "running": "En ejecución",
            "dark_mode": "Modo oscuro",
            "light_mode": "Modo claro",
            "output_title": "Salida",
            "output_subtitle": "Registro de la ejecución.",
            "source_title": "Carpeta fuente",
            "source_subtitle": "Selecciona la carpeta base.",
            "choose_folder": "Elegir carpeta",
            "import_title": "Importación",
            "import_subtitle_running": "Importando playlists en Music.",
            "import_subtitle_idle": "Listo para iniciar la importación.",
            "create_playlists": "Crear playlists",
            "running_button": "Ejecutando...",
            "cancel": "Cancelar",
            "kill_processes": "Matar procesos",
            "progress_title": "Progreso",
            "progress_subtitle_busy": "Procesando archivos...",
            "progress_subtitle_idle": "Sin actividad",
            "progress_ready": "Progreso: listo para iniciar",
            "progress_preparing": "Progreso: preparando...",
            "progress_line": "Progreso: %d/%d  ·  %@  ·  %@",
            "volume": "Volumen de Music: %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Selecciona carpeta",
            "step2": "Revisar y crear",
            "step3": "Progreso y resumen",
            "status_ready": "Listo para comenzar",
            "status_importing": "Importando…",
            "status_done": "Completado",
            "panel_select": "Seleccionar",
            "log_select_first": "Selecciona una carpeta primero.",
            "log_missing_script": "No se encontro el script AppleScript en los recursos.",
            "log_running": "Ejecutando AppleScript...",
            "log_done": "Listo. Revisa Music para ver las playlists.",
            "log_osascript_failed": "No se pudo ejecutar osascript: %@",
            "log_canceled": "Cancelado por el usuario.",
            "log_processes_killed": "Procesos de importacion terminados.",
            "log_kill_failed": "No se pudo terminar procesos: %@",
            "log_folder_selected": "Carpeta seleccionada: %@",
            "volume_unavailable": "Volumen de Music: no disponible",
            "volume_determining": "Volumen de Music: determinando...",
            "elapsed": "Tiempo: %02d:%02d"
        ],
        "English (US)": [
            "title": "Folder to Music",
            "subtitle": "Create folders and playlists in Music from a folder hierarchy.",
            "language": "Language",
            "running": "Running",
            "dark_mode": "Dark mode",
            "light_mode": "Light mode",
            "output_title": "Output",
            "output_subtitle": "Execution log.",
            "source_title": "Source folder",
            "source_subtitle": "Select the base folder.",
            "choose_folder": "Choose folder",
            "import_title": "Import",
            "import_subtitle_running": "Importing playlists into Music.",
            "import_subtitle_idle": "Ready to start importing.",
            "create_playlists": "Create playlists",
            "running_button": "Running...",
            "cancel": "Cancel",
            "kill_processes": "Kill processes",
            "progress_title": "Progress",
            "progress_subtitle_busy": "Processing files...",
            "progress_subtitle_idle": "No activity",
            "progress_ready": "Progress: ready to start",
            "progress_preparing": "Progress: preparing...",
            "progress_line": "Progress: %d/%d  ·  %@  ·  %@",
            "volume": "Music volume: %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Choose folder",
            "step2": "Review & create",
            "step3": "Progress & summary",
            "status_ready": "Ready to start",
            "status_importing": "Importing…",
            "status_done": "Completed",
            "panel_select": "Select",
            "log_select_first": "Select a folder first.",
            "log_missing_script": "AppleScript resource not found.",
            "log_running": "Running AppleScript...",
            "log_done": "Done. Check Music for playlists.",
            "log_osascript_failed": "Failed to run osascript: %@",
            "log_canceled": "Canceled by the user.",
            "log_processes_killed": "Import processes terminated.",
            "log_kill_failed": "Failed to terminate processes: %@",
            "log_folder_selected": "Folder selected: %@",
            "volume_unavailable": "Music volume: unavailable",
            "volume_determining": "Music volume: determining...",
            "elapsed": "Time: %02d:%02d"
        ],
        "English (UK)": [
            "title": "Folder to Music",
            "subtitle": "Create folders and playlists in Music from a folder hierarchy.",
            "language": "Language",
            "running": "Running",
            "dark_mode": "Dark mode",
            "light_mode": "Light mode",
            "output_title": "Output",
            "output_subtitle": "Execution log.",
            "source_title": "Source folder",
            "source_subtitle": "Select the base folder.",
            "choose_folder": "Choose folder",
            "import_title": "Import",
            "import_subtitle_running": "Importing playlists into Music.",
            "import_subtitle_idle": "Ready to start importing.",
            "create_playlists": "Create playlists",
            "running_button": "Running...",
            "cancel": "Cancel",
            "kill_processes": "Kill processes",
            "progress_title": "Progress",
            "progress_subtitle_busy": "Processing files...",
            "progress_subtitle_idle": "No activity",
            "progress_ready": "Progress: ready to start",
            "progress_preparing": "Progress: preparing...",
            "progress_line": "Progress: %d/%d  ·  %@  ·  %@",
            "volume": "Music volume: %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Choose folder",
            "step2": "Review & create",
            "step3": "Progress & summary",
            "status_ready": "Ready to start",
            "status_importing": "Importing…",
            "status_done": "Completed",
            "panel_select": "Select",
            "log_select_first": "Select a folder first.",
            "log_missing_script": "AppleScript resource not found.",
            "log_running": "Running AppleScript...",
            "log_done": "Done. Check Music for playlists.",
            "log_osascript_failed": "Failed to run osascript: %@",
            "log_canceled": "Canceled by the user.",
            "log_processes_killed": "Import processes terminated.",
            "log_kill_failed": "Failed to terminate processes: %@",
            "log_folder_selected": "Folder selected: %@",
            "volume_unavailable": "Music volume: unavailable",
            "volume_determining": "Music volume: determining...",
            "elapsed": "Time: %02d:%02d"
        ],
        "Français": [
            "title": "Folder to Music",
            "subtitle": "Crée des dossiers et des playlists dans Music depuis une hiérarchie de dossiers.",
            "language": "Langue",
            "running": "En cours",
            "dark_mode": "Mode sombre",
            "light_mode": "Mode clair",
            "output_title": "Sortie",
            "output_subtitle": "Journal d'exécution.",
            "source_title": "Dossier source",
            "source_subtitle": "Sélectionnez le dossier de base.",
            "choose_folder": "Choisir le dossier",
            "import_title": "Importation",
            "import_subtitle_running": "Importation des playlists dans Music.",
            "import_subtitle_idle": "Prêt à démarrer l'importation.",
            "create_playlists": "Créer des playlists",
            "running_button": "En cours...",
            "cancel": "Annuler",
            "kill_processes": "Arrêter les processus",
            "progress_title": "Progression",
            "progress_subtitle_busy": "Traitement des fichiers...",
            "progress_subtitle_idle": "Aucune activité",
            "progress_ready": "Progression : prêt à démarrer",
            "progress_preparing": "Progression : préparation...",
            "progress_line": "Progression : %d/%d  ·  %@  ·  %@",
            "volume": "Volume de Music : %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Choisir un dossier",
            "step2": "Vérifier et créer",
            "step3": "Progression et résumé",
            "status_ready": "Prêt à démarrer",
            "status_importing": "Importation…",
            "status_done": "Terminé",
            "panel_select": "Sélectionner",
            "log_select_first": "Sélectionnez d'abord un dossier.",
            "log_missing_script": "Ressource AppleScript introuvable.",
            "log_running": "Exécution de l'AppleScript...",
            "log_done": "Terminé. Vérifiez Music pour les playlists.",
            "log_osascript_failed": "Échec de l'exécution d'osascript : %@",
            "log_canceled": "Annulé par l'utilisateur.",
            "log_processes_killed": "Processus d'importation arrêtés.",
            "log_kill_failed": "Impossible d'arrêter les processus : %@",
            "log_folder_selected": "Dossier sélectionné : %@",
            "volume_unavailable": "Volume de Music : indisponible",
            "volume_determining": "Volume de Music : détermination...",
            "elapsed": "Temps : %02d:%02d"
        ],
        "Deutsch": [
            "title": "Folder to Music",
            "subtitle": "Erstellt Ordner und Playlists in Music aus einer Ordnerhierarchie.",
            "language": "Sprache",
            "running": "Wird ausgeführt",
            "dark_mode": "Dunkelmodus",
            "light_mode": "Hellmodus",
            "output_title": "Ausgabe",
            "output_subtitle": "Ausführungsprotokoll.",
            "source_title": "Quellordner",
            "source_subtitle": "Wähle den Basisordner aus.",
            "choose_folder": "Ordner wählen",
            "import_title": "Import",
            "import_subtitle_running": "Playlists werden in Music importiert.",
            "import_subtitle_idle": "Bereit zum Import.",
            "create_playlists": "Playlists erstellen",
            "running_button": "Läuft...",
            "cancel": "Abbrechen",
            "kill_processes": "Prozesse beenden",
            "progress_title": "Fortschritt",
            "progress_subtitle_busy": "Dateien werden verarbeitet...",
            "progress_subtitle_idle": "Keine Aktivität",
            "progress_ready": "Fortschritt: bereit zum Start",
            "progress_preparing": "Fortschritt: wird vorbereitet...",
            "progress_line": "Fortschritt: %d/%d  ·  %@  ·  %@",
            "volume": "Music-Lautstärke: %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Ordner wählen",
            "step2": "Prüfen & erstellen",
            "step3": "Fortschritt & Übersicht",
            "status_ready": "Bereit zum Start",
            "status_importing": "Importiere…",
            "status_done": "Abgeschlossen",
            "panel_select": "Auswählen",
            "log_select_first": "Wähle zuerst einen Ordner.",
            "log_missing_script": "AppleScript-Ressource nicht gefunden.",
            "log_running": "AppleScript wird ausgeführt...",
            "log_done": "Fertig. Prüfe Music für Playlists.",
            "log_osascript_failed": "Ausführen von osascript fehlgeschlagen: %@",
            "log_canceled": "Vom Benutzer abgebrochen.",
            "log_processes_killed": "Importprozesse beendet.",
            "log_kill_failed": "Prozesse konnten nicht beendet werden: %@",
            "log_folder_selected": "Ordner ausgewählt: %@",
            "volume_unavailable": "Music-Lautstärke: nicht verfügbar",
            "volume_determining": "Music-Lautstärke: wird ermittelt...",
            "elapsed": "Zeit: %02d:%02d"
        ],
        "Italiano": [
            "title": "Folder to Music",
            "subtitle": "Crea cartelle e playlist in Music da una gerarchia di cartelle.",
            "language": "Lingua",
            "running": "In esecuzione",
            "dark_mode": "Modalità scura",
            "light_mode": "Modalità chiara",
            "output_title": "Output",
            "output_subtitle": "Registro di esecuzione.",
            "source_title": "Cartella sorgente",
            "source_subtitle": "Seleziona la cartella di base.",
            "choose_folder": "Scegli cartella",
            "import_title": "Importazione",
            "import_subtitle_running": "Importazione delle playlist in Music.",
            "import_subtitle_idle": "Pronto per avviare l'importazione.",
            "create_playlists": "Crea playlist",
            "running_button": "In esecuzione...",
            "cancel": "Annulla",
            "kill_processes": "Termina processi",
            "progress_title": "Avanzamento",
            "progress_subtitle_busy": "Elaborazione file...",
            "progress_subtitle_idle": "Nessuna attività",
            "progress_ready": "Avanzamento: pronto per iniziare",
            "progress_preparing": "Avanzamento: preparazione...",
            "progress_line": "Avanzamento: %d/%d  ·  %@  ·  %@",
            "volume": "Volume Music: %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Scegli cartella",
            "step2": "Rivedi e crea",
            "step3": "Avanzamento e riepilogo",
            "status_ready": "Pronto per iniziare",
            "status_importing": "Importazione…",
            "status_done": "Completato",
            "panel_select": "Seleziona",
            "log_select_first": "Seleziona prima una cartella.",
            "log_missing_script": "Risorsa AppleScript non trovata.",
            "log_running": "Esecuzione AppleScript...",
            "log_done": "Fatto. Controlla Music per le playlist.",
            "log_osascript_failed": "Impossibile eseguire osascript: %@",
            "log_canceled": "Annullato dall'utente.",
            "log_processes_killed": "Processi di importazione terminati.",
            "log_kill_failed": "Impossibile terminare i processi: %@",
            "log_folder_selected": "Cartella selezionata: %@",
            "volume_unavailable": "Volume Music: non disponibile",
            "volume_determining": "Volume Music: determinazione...",
            "elapsed": "Tempo: %02d:%02d"
        ],
        "Português (PT)": [
            "title": "Folder to Music",
            "subtitle": "Cria pastas e playlists no Music a partir de uma hierarquia de pastas.",
            "language": "Idioma",
            "running": "Em execução",
            "dark_mode": "Modo escuro",
            "light_mode": "Modo claro",
            "output_title": "Saída",
            "output_subtitle": "Registo de execução.",
            "source_title": "Pasta de origem",
            "source_subtitle": "Seleciona a pasta base.",
            "choose_folder": "Escolher pasta",
            "import_title": "Importação",
            "import_subtitle_running": "A importar playlists no Music.",
            "import_subtitle_idle": "Pronto para iniciar a importação.",
            "create_playlists": "Criar playlists",
            "running_button": "Em execução...",
            "cancel": "Cancelar",
            "kill_processes": "Terminar processos",
            "progress_title": "Progresso",
            "progress_subtitle_busy": "A processar ficheiros...",
            "progress_subtitle_idle": "Sem atividade",
            "progress_ready": "Progresso: pronto para iniciar",
            "progress_preparing": "Progresso: a preparar...",
            "progress_line": "Progresso: %d/%d  ·  %@  ·  %@",
            "volume": "Volume do Music: %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Escolher pasta",
            "step2": "Rever e criar",
            "step3": "Progresso e resumo",
            "status_ready": "Pronto para iniciar",
            "status_importing": "A importar…",
            "status_done": "Concluído",
            "panel_select": "Selecionar",
            "log_select_first": "Seleciona uma pasta primeiro.",
            "log_missing_script": "Recurso AppleScript não encontrado.",
            "log_running": "A executar AppleScript...",
            "log_done": "Concluído. Verifica o Music para as playlists.",
            "log_osascript_failed": "Falha ao executar osascript: %@",
            "log_canceled": "Cancelado pelo utilizador.",
            "log_processes_killed": "Processos de importação terminados.",
            "log_kill_failed": "Não foi possível terminar processos: %@",
            "log_folder_selected": "Pasta selecionada: %@",
            "volume_unavailable": "Volume do Music: indisponível",
            "volume_determining": "Volume do Music: a determinar...",
            "elapsed": "Tempo: %02d:%02d"
        ],
        "Nederlands": [
            "title": "Folder to Music",
            "subtitle": "Maak mappen en playlists in Music vanuit een mapstructuur.",
            "language": "Taal",
            "running": "Bezig",
            "dark_mode": "Donkere modus",
            "light_mode": "Lichte modus",
            "output_title": "Uitvoer",
            "output_subtitle": "Uitvoeringslog.",
            "source_title": "Bronmap",
            "source_subtitle": "Selecteer de basismap.",
            "choose_folder": "Map kiezen",
            "import_title": "Importeren",
            "import_subtitle_running": "Playlists worden in Music geïmporteerd.",
            "import_subtitle_idle": "Klaar om te importeren.",
            "create_playlists": "Playlists maken",
            "running_button": "Bezig...",
            "cancel": "Annuleren",
            "kill_processes": "Processen stoppen",
            "progress_title": "Voortgang",
            "progress_subtitle_busy": "Bestanden verwerken...",
            "progress_subtitle_idle": "Geen activiteit",
            "progress_ready": "Voortgang: klaar om te starten",
            "progress_preparing": "Voortgang: voorbereiden...",
            "progress_line": "Voortgang: %d/%d  ·  %@  ·  %@",
            "volume": "Music-volume: %d",
            "footer": "created by marquesedition © 2026",
            "step1": "Map kiezen",
            "step2": "Controleren & maken",
            "step3": "Voortgang & samenvatting",
            "status_ready": "Klaar om te starten",
            "status_importing": "Importeren…",
            "status_done": "Voltooid",
            "panel_select": "Selecteren",
            "log_select_first": "Kies eerst een map.",
            "log_missing_script": "AppleScript-resource niet gevonden.",
            "log_running": "AppleScript uitvoeren...",
            "log_done": "Klaar. Controleer Music voor playlists.",
            "log_osascript_failed": "Kan osascript niet uitvoeren: %@",
            "log_canceled": "Geannuleerd door de gebruiker.",
            "log_processes_killed": "Importprocessen beëindigd.",
            "log_kill_failed": "Processen beëindigen mislukt: %@",
            "log_folder_selected": "Map geselecteerd: %@",
            "volume_unavailable": "Music-volume: niet beschikbaar",
            "volume_determining": "Music-volume: bepalen...",
            "elapsed": "Tijd: %02d:%02d"
        ]
    ]
}
